#include <algorithm>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <string>
#include <utility>
#include <vector>

#include "llvm/Support/FileSystem.h"

#include "codegen/codegen.hpp"
#include "codegen/functions.hpp"
#include "codegen/package.hpp"
#include "codegen/utils.hpp"
#include "flu/diagnostics.hpp"
#include "flu/symbols.hpp"
#include "pipeline.hpp"
#include "traversal.hpp"

using namespace codegen;

// ===========================================================================
// Converter-producer closure
//
// A wrapped module that exchanges a foreign derived type across its API
// use-associates that type's converters from the *producer's* wrapper
// module. Those converters are module procedures, so a producer left out of
// the wrap set is a compile error in the consumer's wrapper, not something the
// user can fix after the fact. The wrap set is therefore closed over the
// modules owning those types.
//
// The scan mirrors the four places codegen records a Foreign type
// (note_ext_type): procedure dummies, ctor kwargs, inline scalar components,
// and module variables. It classifies with codegen's own classify_dtype so the
// closure cannot drift from what codegen actually emits, and it deliberately
// touches nothing that reports diagnostics -- it runs before codegen and, on
// promotion, again after re-traversal.
// ===========================================================================

static void note_owner(sema::DeclTypeSpec const *t, module_info_t const &m,
                       std::set<std::string> &out) {
  if (t == nullptr)
    return;
  if (auto const c = classify_dtype(*t, m); c.cls == dtype_class::Foreign)
    out.insert(fold_lower(c.owner));
}

// Dummies of a procedure symbol; `sym` may be a type-bound binding.
static void scan_dummies(sema::Symbol const &sym, module_info_t const &m,
                         std::set<std::string> &out) {
  sema::Symbol const *proc = &sym;
  if (auto const *actual = flu::binding_actual(sym))
    proc = actual;
  auto const *sub = proc->detailsIf<sema::SubprogramDetails>();
  if (sub == nullptr)
    return;
  for (sema::Symbol const *d : sub->dummyArgs())
    if (d != nullptr)
      note_owner(d->GetType(), m, out);
}

static void scan_generic(sema::Symbol const &generic, module_info_t const &m,
                         std::set<std::string> &out) {
  for (auto const &spec : flu::get_specific_procs(generic))
    scan_dummies(spec, m, out);
}

static std::set<std::string>
converter_producers(std::vector<module_info_t> const &modules) {
  std::set<std::string> owners;
  for (auto const &m : modules) {
    for (auto const &fn : m.functions)
      if (fn.ptr != nullptr)
        scan_dummies(*fn.ptr, m, owners);
    for (auto const &iface : m.interfaces)
      if (iface.ptr != nullptr)
        scan_generic(*iface.ptr, m, owners);
    for (sym_ptr_t v : m.variables)
      if (v != nullptr)
        note_owner(v->GetType(), m, owners);

    for (auto const &[name, dt] : m.derived_types) {
      if (dt.ptr == nullptr)
        continue;
      if (dt.ctor.ptr != nullptr)
        scan_generic(*dt.ctor.ptr, m, owners);
      if (dt.init.ptr != nullptr)
        scan_dummies(*dt.init.ptr, m, owners);
      for (auto const &mth : dt.methods)
        if (mth.ptr != nullptr)
          scan_dummies(*mth.ptr, m, owners);
      // Same accept condition as public_fields, minus its warnings: only
      // inline scalar derived components become properties.
      for (auto const &comp : flu::public_components(*dt.ptr))
        if (flu::rank_of(comp) == 0 && !flu::is_pointer(comp) &&
            !flu::is_allocatable(comp))
          note_owner(comp->GetType(), m, owners);
    }
  }
  return owners;
}

// The compilation database records compile steps only, so the link inputs
// (the project's objects or libraries) cannot be derived and stay a
// user-filled variable. Wrappers are compiled dependency-first (submods
// arrives in that order): consumer wrappers use-associate the producer
// wrappers' converters, and `-I .` makes the sibling .mod files visible.
static std::string build_script(pkg_info_t const &pkg,
                                std::vector<std::string> const &submods,
                                std::vector<std::string> const &folded_names) {
  std::string s;
  s += "#!/bin/sh\n";
  s += "# Generated by flair-f2py -- do not edit.\n";
  s += "# Builds the combined Python extension " + pkg.name +
       ".so from the generated wrappers.\n";
  s += "#\n";
  s += "# FC            Fortran compiler; must be the flang toolchain used "
       "to build the project.\n";
  s += "# FLAIR_RUNTIME flair's Fortran binding of the Python/NumPy C API.\n";
  s += "# PROJ_LIBS     objects or libraries providing the wrapped modules' "
       "implementations\n";
  s += "#               (the compilation database records no link step, so "
       "fill these in).\n";
  s += "set -eu\n";
  s += ": \"${FC:=flang}\"\n";
  s += ": \"${FLAIR_RUNTIME:=" + pkg.runtime_src + "}\"\n";
  s += ": \"${PROJ_LIBS:=}\"\n";
  s += "\n";
  s += "$FC -fPIC -c \"$FLAIR_RUNTIME\" -o fortran_python_api.o\n";
  std::string objs = "fortran_python_api.o";
  for (size_t i = 0; i < submods.size(); ++i) {
    std::string dirs;
    if (auto it = pkg.module_search_dirs.find(folded_names[i]);
        it != pkg.module_search_dirs.end())
      for (auto const &d : it->second)
        dirs += " -I \"" + d + "\"";
    s += "$FC -fPIC -I ." + dirs + " -c py_" + submods[i] + ".F90\n";
    objs += " py_" + submods[i] + ".o";
  }
  s += "$FC -fPIC -I . -c py_" + pkg.name + "_pkg.F90\n";
  objs += " py_" + pkg.name + "_pkg.o";
  s += "$FC -shared " + objs + " $PROJ_LIBS -o " + pkg.name +
       ".so -Wl,-rpath,'$ORIGIN'\n";
  return s;
}

// Combined-package emission: per-module wrappers with internal inits, the
// package PyInit file, and the build script. Project-level name clashes
// have no symbol to attach a message to, so they go to `out` directly.
static bool
package_outputs(wdata_t &wdata, llvm::raw_ostream &out,
                std::vector<std::pair<std::string, std::string>> &outputs) {
  pkg_info_t const &pkg = *wdata.pkg;

  std::vector<std::string> submods, folded_names;
  std::map<std::string, std::string> seen; // pyname -> Fortran module
  bool ok = true;
  for (auto const &mi : wdata.modules) {
    if (not has_wrappable(mi))
      continue;
    std::string const modpy = module_pyname(mi.name);
    if (auto const [it, inserted] = seen.emplace(modpy, mi.name);
        not inserted) {
      out << "flair-f2py: modules '" << it->second << "' and '" << mi.name
          << "' both map to python module '" << modpy
          << "'; rename one or wrap them separately\n";
      ok = false;
    }
    if (modpy == pkg.name + "_pkg") {
      out << "flair-f2py: module '" << mi.name
          << "' collides with the generated package file 'py_" << modpy
          << ".F90'; rename it or choose another --pkg name\n";
      ok = false;
    }
    submods.push_back(modpy);
    folded_names.push_back(fold_lower(mi.name));
  }
  if (submods.empty()) {
    out << "flair-f2py: no wrappable modules in the USE closure; nothing to "
           "package\n";
    return false;
  }
  if (not ok)
    return false;

  for (auto const &mi : wdata.modules) {
    if (not has_wrappable(mi))
      continue;
    outputs.emplace_back("py_" + module_pyname(mi.name) + ".F90",
                         codegen_module(mi, /*internal_init=*/true));
  }
  outputs.emplace_back("py_" + pkg.name + "_pkg.F90",
                       codegen_package(pkg.name, submods));
  outputs.emplace_back("build_" + pkg.name + ".sh",
                       build_script(pkg, submods, folded_names));
  return true;
}

bool run_wrap_pipeline(sema::SemanticsContext &context,
                       std::shared_ptr<wdata_t> wdata, llvm::raw_ostream &out) {
  traverse_global_scope(context.globalScope(), wdata, context);

  // Close the wrap set over its converter producers. Promoting one module can
  // expose foreign types of its own, so re-traverse until nothing new appears;
  // `wrap_modules` only grows and is bounded by the modules in scope, and a
  // producer that is not in scope at all (wrappable only by a separate run)
  // simply never shows up, leaving note_ext_type's warning to say so.
  while (not wdata->wrap_files.empty()) {
    std::set<std::string> wrapped;
    for (auto const &mi : wdata->modules)
      wrapped.insert(fold_lower(mi.name));

    bool promoted = false;
    for (auto const &owner : converter_producers(wdata->modules))
      if (wrapped.count(owner) == 0 && wdata->wrap_modules.insert(owner).second)
        promoted = true;
    if (not promoted)
      break;

    wdata->modules.clear();
    traverse_global_scope(context.globalScope(), wdata, context);
  }

  // Order wrapper modules dependency-first (depgraph post-order): a consumer
  // wrapper use-associates the producer wrapper's converters, so the producer
  // must be emitted, compiled, and init'ed before its consumers.
  if (wdata->pkg && not wdata->pkg->module_order.empty()) {
    auto const &order = wdata->pkg->module_order;
    auto const rank = [&](module_info_t const &mi) {
      return static_cast<size_t>(
          std::find(order.begin(), order.end(), fold_lower(mi.name)) -
          order.begin());
    };
    std::stable_sort(
        wdata->modules.begin(), wdata->modules.end(),
        [&](auto const &a, auto const &b) { return rank(a) < rank(b); });
  }

  note_run_modules(wdata->modules);
  // Python-visible names carry the package prefix; set it either way so it
  // cannot leak from a previous run into a single-mode one.
  set_package_prefix(wdata->pkg ? wdata->pkg->name : std::string{});
  std::vector<std::pair<std::string, std::string>> outputs;
  bool ok = true;
  if (wdata->pkg) {
    ok = package_outputs(*wdata, out, outputs);
  } else {
    for (auto const &mi : wdata->modules) {
      if (not has_wrappable(mi))
        continue;
      outputs.emplace_back("py_" + module_pyname(mi.name) + ".F90",
                           codegen_module(mi));
    }
  }
  wdata->modules.clear();

  bool const failed =
      context.messages().AnyFatalError(context.warningsAreErrors());
  flu::flush_messages(context, out);
  if (failed || not ok)
    return false;

  for (auto const &[outfile, content] : outputs) {
    std::ofstream(outfile) << content;
    if (llvm::StringRef(outfile).ends_with(".sh"))
      llvm::sys::fs::setPermissions(outfile,
                                    static_cast<llvm::sys::fs::perms>(0755));
    std::cout << "Generated " << outfile << std::endl;
  }
  return true;
}
