#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <utility>
#include <vector>

#include "llvm/Support/FileSystem.h"

#include "codegen/codegen.hpp"
#include "codegen/functions.hpp"
#include "codegen/package.hpp"
#include "codegen/utils.hpp"
#include "flu/diagnostics.hpp"
#include "pipeline.hpp"
#include "traversal.hpp"

using namespace codegen;

// The compilation database records compile steps only, so the link inputs
// (the project's objects or libraries) cannot be derived and stay a
// user-filled variable.
static std::string build_script(pkg_info_t const &pkg,
                                std::vector<std::string> const &submods,
                                std::vector<std::string> const &folded_names) {
  std::string s;
  s += "#!/bin/sh\n";
  s += "# Generated by flair-f2py -- do not edit.\n";
  s += "# Builds the combined Python extension " + pkg.name +
       ".so from the generated wrappers.\n";
  s += "#\n";
  s += "# FC            Fortran compiler; must be the flang toolchain used "
       "to build the project.\n";
  s += "# FLAIR_RUNTIME flair's Fortran binding of the Python/NumPy C API.\n";
  s += "# PROJ_LIBS     objects or libraries providing the wrapped modules' "
       "implementations\n";
  s += "#               (the compilation database records no link step, so "
       "fill these in).\n";
  s += "set -eu\n";
  s += ": \"${FC:=flang}\"\n";
  s += ": \"${FLAIR_RUNTIME:=" + pkg.runtime_src + "}\"\n";
  s += ": \"${PROJ_LIBS:=}\"\n";
  s += "\n";
  s += "$FC -fPIC -c \"$FLAIR_RUNTIME\" -o fortran_python_api.o\n";
  std::string objs = "fortran_python_api.o";
  for (size_t i = 0; i < submods.size(); ++i) {
    std::string dirs;
    if (auto it = pkg.module_search_dirs.find(folded_names[i]);
        it != pkg.module_search_dirs.end())
      for (auto const &d : it->second)
        dirs += " -I \"" + d + "\"";
    s += "$FC -fPIC -I ." + dirs + " -c py_" + submods[i] + ".F90\n";
    objs += " py_" + submods[i] + ".o";
  }
  s += "$FC -fPIC -I . -c py_" + pkg.name + "_pkg.F90\n";
  objs += " py_" + pkg.name + "_pkg.o";
  s += "$FC -shared " + objs + " $PROJ_LIBS -o " + pkg.name +
       ".so -Wl,-rpath,'$ORIGIN'\n";
  return s;
}

// Combined-package emission: per-module wrappers with internal inits, the
// package PyInit file, and the build script. Project-level name clashes
// have no symbol to attach a message to, so they go to `out` directly.
static bool
package_outputs(wdata_t &wdata, llvm::raw_ostream &out,
                std::vector<std::pair<std::string, std::string>> &outputs) {
  pkg_info_t const &pkg = *wdata.pkg;

  std::vector<std::string> submods, folded_names;
  std::map<std::string, std::string> seen; // pyname -> Fortran module
  bool ok = true;
  for (auto const &mi : wdata.modules) {
    if (not has_wrappable(mi))
      continue;
    std::string const modpy = module_pyname(mi.name);
    if (auto const [it, inserted] = seen.emplace(modpy, mi.name);
        not inserted) {
      out << "flair-f2py: modules '" << it->second << "' and '" << mi.name
          << "' both map to python module '" << modpy
          << "'; rename one or wrap them separately\n";
      ok = false;
    }
    if (modpy == pkg.name + "_pkg") {
      out << "flair-f2py: module '" << mi.name
          << "' collides with the generated package file 'py_" << modpy
          << ".F90'; rename it or choose another --pkg name\n";
      ok = false;
    }
    submods.push_back(modpy);
    folded_names.push_back(fold_lower(mi.name));
  }
  if (submods.empty()) {
    out << "flair-f2py: no wrappable modules in the USE closure; nothing to "
           "package\n";
    return false;
  }
  if (not ok)
    return false;

  for (auto const &mi : wdata.modules) {
    if (not has_wrappable(mi))
      continue;
    outputs.emplace_back("py_" + module_pyname(mi.name) + ".F90",
                         codegen_module(mi, /*internal_init=*/true));
  }
  outputs.emplace_back("py_" + pkg.name + "_pkg.F90",
                       codegen_package(pkg.name, submods));
  outputs.emplace_back("build_" + pkg.name + ".sh",
                       build_script(pkg, submods, folded_names));
  return true;
}

bool run_wrap_pipeline(sema::SemanticsContext &context,
                       std::shared_ptr<wdata_t> wdata, llvm::raw_ostream &out) {
  traverse_global_scope(context.globalScope(), wdata, context);

  note_run_modules(wdata->modules);
  std::vector<std::pair<std::string, std::string>> outputs;
  bool ok = true;
  if (wdata->pkg) {
    ok = package_outputs(*wdata, out, outputs);
  } else {
    for (auto const &mi : wdata->modules) {
      if (not has_wrappable(mi))
        continue;
      outputs.emplace_back("py_" + module_pyname(mi.name) + ".F90",
                           codegen_module(mi));
    }
  }
  wdata->modules.clear();

  bool const failed =
      context.messages().AnyFatalError(context.warningsAreErrors());
  flu::flush_messages(context, out);
  if (failed || not ok)
    return false;

  for (auto const &[outfile, content] : outputs) {
    std::ofstream(outfile) << content;
    if (llvm::StringRef(outfile).ends_with(".sh"))
      llvm::sys::fs::setPermissions(outfile,
                                    static_cast<llvm::sys::fs::perms>(0755));
    std::cout << "Generated " << outfile << std::endl;
  }
  return true;
}
